### ISSUE TITLE
support existingSecret pattern

### ISSUE THREAD

**Issue by nicorikken** [cetic/helm-pgadmin#14]
The chart currently only supports a default admin password by defining it in the `values.yaml`. I want to provide a more secure password, but don't want to do so in plaintext in the `values.yaml`, but rather create one from a [sealed secret](https://github.com/bitnami-labs/sealed-secrets).
To support this use-case, I want to add the `existingSecret` pattern to the chart, which also allows you to define the name of a secret that is already supposed to be in the cluster.

By introducing a helper, the proper default fallback can be included.

**Comment by alexnuttinck** [comment]
Hello @nicorikken, Thanks for the the proposal, it will be useful! I look into your PR now.

**Comment by alexnuttinck** [comment]
Merged in [0.1.12](https://github.com/cetic/helm-pgadmin/releases/tag/0.1.12). Thanks.
