### ISSUE TITLE
Set existing secret for TLS

### ISSUE THREAD

**Issue by tpoxa** [cetic/helm-pgadmin#2]
For someone (like me) would be useful to have ability use existing secret name without issuer

**Comment by alexnuttinck** [comment]
Hello @tpoxa, thanks for the remark. I have made some modifications to support your request. With my last [commit](https://github.com/cetic/helm-pgadmin/commit/42974bc2e3f93a79863fa510c9db51c77c353bef), you should be able to use existing secrets via the `ingress.tls` variable.  Could you check it and tell me if you think it resolves your request?

**Comment by alexnuttinck** [comment]
As no answer, I will merge this fix into master, @tpoxa feel free to re-open this issue if there is any problem.

**Comment by tpoxa** [comment]
Thank you for update. Works great!
